m1 = Movie.create(title:'titanic')
m2 = Movie.create(title:'v for vendetta')
m3 = Movie.create(title:'atonement')
m4 = Movie.create(title:'road to pedition')
m5 = Movie.create(title:'wild target')
m6 = Movie.create(title:'happy gilmore')
m7 = Movie.create(title:'madagascar')

s1 = Song.create(title:'i found a reason')
s2 = Song.create(title:'out of sight')
s3 = Song.create(title:'my heart will go on')
s4 = Song.create(title:'a life so changed')
s5 = Song.create(title:'ghosts')
s6 = Song.create(title:'in a mellow mood')
s7 = Song.create(title:'with my own eyes')
s8 = Song.create(title:'chariots of fire theme')

# Moviesong.create(movie_id: m1.id, song_id: s1.id)
MovieSong.create(movie: m1, song: s3)
MovieSong.create(movie: m2, song: s1)
MovieSong.create(movie: m3, song: s7)
MovieSong.create(movie: m1, song: s4)
MovieSong.create(movie: m4, song: s7)
MovieSong.create(movie: m5, song: s6)
MovieSong.create(song: s8, movie: m7)
MovieSong.create(song: s8, movie: m6)

User.create(name: 'Alex')
User.create(name: 'Mike')
User.create(name: 'Alice')
